-- Generated by Noctalia's Template Processor. Do not edit manually.
-- 源模板：dotfiles/noctalia/templates/neovim.lua
return {
  base00 = '{{colors.background.default.hex}}',
  base01 = '{{colors.surface_container.default.hex}}',
  base02 = '{{colors.surface_container_high.default.hex}}',
  base03 = '{{colors.outline.default.hex}}',
  base04 = '{{colors.on_surface_variant.default.hex}}',
  base05 = '{{colors.on_surface.default.hex}}',
  base06 = '{{colors.on_background.default.hex}}',
  base07 = '{{colors.inverse_surface.default.hex}}',
  base08 = '{{colors.error.default.hex}}',
  base09 = '{{colors.tertiary.default.hex}}',
  base0A = '{{colors.terminal_normal_yellow.default.hex}}',
  base0B = '{{colors.terminal_normal_green.default.hex}}',
  base0C = '{{colors.terminal_normal_cyan.default.hex}}',
  base0D = '{{colors.primary.default.hex}}',
  base0E = '{{colors.terminal_normal_magenta.default.hex}}',
  base0F = '{{colors.terminal_bright_red.default.hex}}',
}
