# Mango 专用 Foot 外观；独立于 Noctalia 动态生成的 Niri 主题。
font=JetBrainsMono Nerd Font:size=18
pad=10x10 center
selection-target=clipboard

[colors-dark]
alpha=0.88
background=201b14
foreground=ebdbb2
regular0=282828
regular1=cc241d
regular2=98971a
regular3=d79921
regular4=458588
regular5=b16286
regular6=689d6a
regular7=a89984
bright0=928374
bright1=fb4934
bright2=b8bb26
bright3=fabd2f
bright4=83a598
bright5=d3869b
bright6=8ec07c
bright7=ebdbb2

[cursor]
style=beam

[scrollback]
lines=10000
