# Mango 环境变量：GTK Wayland 使用原生 text-input-v3；强制 GTK_IM_MODULE 会触发 Fcitx 诊断并绕过原生前端。
env=QT_IM_MODULE,fcitx
env=SDL_IM_MODULE,fcitx
env=XMODIFIERS,@im=fcitx
env=QT_QPA_PLATFORM,wayland;xcb
env=XCURSOR_THEME,Bibata-Modern-Classic
env=XCURSOR_SIZE,24
